[project]

name = "speech-to-text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai-whisper>=20240930",
    "tiktoken>=0.9.0",
    "torch>=2.6.0",
]
